import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { WorkflowSpec } from './workflow.js';
import {
  DEFAULT_PLUGIN_RESPONSE_POLICY,
  PLUGIN_SKILLS_DIR,
  deletePluginSkill,
  ensurePluginSkills,
  filterPluginGenerationArgs,
  generatePluginSkill,
  isAutoGeneratedSkill,
  parsePluginResponsePolicy,
  pluginResponseAllows,
  pluginSkillPath,
  readPluginSkill,
  syncPluginSkill,
  writeCustomSkill,
  writePluginSkill,
} from './workflow-skill.js';

const baseSpec = (over: Partial<WorkflowSpec> = {}): WorkflowSpec => ({
  id: 'test_plugin',
  name: '测试插件',
  description: '用于测试的插件',
  inputs: [
    { id: 'text-1', kind: 'text', label: '提示词', nodeId: '1', field: 'text', classType: 'CLIPTextEncode', primary: true },
    { id: 'image-2', kind: 'image', label: '参考图', nodeId: '2', field: 'image', classType: 'LoadImage', required: true },
    { id: 'hidden-text', kind: 'text', label: '内部文本', nodeId: '9', field: 'text', classType: 'CLIPTextEncode', hidden: true },
  ],
  params: [
    { id: 'steps-3', label: '采样步数', nodeId: '3', field: 'steps', type: 'INT', default: 20, min: 1, max: 150, step: 1, description: '越大细节越多' },
    { id: 'sampler-4', label: '采样器', nodeId: '4', field: 'sampler_name', type: 'combo', default: 'euler', options: ['euler', 'dpmpp_2m'], description: '采样器选择' },
    { id: 'lora-5', label: 'LoRA（多选）', nodeId: '5', field: 'lora', type: 'combo', default: [], multiple: true, strengthable: true, min: -2, max: 2, step: 0.1, applyTo: ['6', '7'] },
    { id: 'internal-cfg', label: '内部 CFG', nodeId: '4', field: 'cfg', type: 'FLOAT', default: 7, llm: false },
    { id: 'hidden-param', label: '隐藏参数', nodeId: '3', field: 'seed', type: 'SEED', default: 42, hidden: true },
  ],
  outputs: [
    { id: 'images-8', kind: 'image', label: '最终图片', nodeId: '8', classType: 'SaveImage' },
    { id: 'hidden-out', kind: 'text', label: '内部输出', nodeId: '9', classType: 'PreviewAny', hidden: true },
  ],
  ...over,
});

describe('generatePluginSkill', () => {
  it('只生成插件上下文，不生成旧版回复协议内容', () => {
    const md = generatePluginSkill(baseSpec());
    expect(md).toMatch(/^---\nname: test_plugin/);
    expect(md).toContain('自动生成');
    expect(md).not.toContain('response:');
    expect(md).not.toContain('thinking: collapsed');
    expect(md).not.toContain('prompt: visible');
    expect(md).not.toContain('route: visible');
    expect(md).not.toContain('result: outside-bubble');
    expect(md).not.toContain('## 回复协议');
  });

  it('只暴露未隐藏且 llm !== false 的输入/参数/输出', () => {
    const md = generatePluginSkill(baseSpec());
    expect(md).toContain('steps-3');
    expect(md).toContain('sampler-4');
    expect(md).toContain('lora-5');
    expect(md).not.toContain('internal-cfg');
    expect(md).not.toContain('hidden-param');
    expect(md).not.toContain('hidden-text');
    expect(md).not.toContain('hidden-out');
    expect(md).not.toContain('内部文本');
  });

  it('参数标注类型/默认值/范围/选项/applyTo 联动', () => {
    const md = generatePluginSkill(baseSpec());
    expect(md).toMatch(/steps-3.*整数/);
    expect(md).toMatch(/默认 20/);
    expect(md).toMatch(/1 ~ 150，步长 1/);
    expect(md).toMatch(/euler、dpmpp_2m/);
    expect(md).toMatch(/多选（每项可调强度）/);
    expect(md).toMatch(/同时作用于节点 6、7/);
    expect(md).toMatch(/越大细节越多/);
  });

  it('文本输入标注 primary，必传参考图生成使用规则', () => {
    const md = generatePluginSkill(baseSpec());
    expect(md).toMatch(/提示词/);
    expect(md).toMatch(/primary/);
    expect(md).toMatch(/必须按顺序传入 1 张参考图/);
  });

  it('无文本输入时推导"不接受提示词"规则', () => {
    const md = generatePluginSkill(baseSpec({ inputs: baseSpec().inputs.filter(i => i.kind !== 'text') }));
    expect(md).toMatch(/不接受提示词/);
  });

  it('combo 选项超过 8 个时截断展示', () => {
    const md = generatePluginSkill(baseSpec({
      params: [{ id: 'combo-1', label: '模型', nodeId: '1', field: 'model', type: 'combo', default: 'a', options: Array.from({ length: 12 }, (_, i) => `model${i}.safetensors`) }],
    }));
    expect(md).toMatch(/model0\.safetensors/);
    expect(md).toMatch(/…/);
    expect(md).not.toContain('model11.safetensors');
  });
});

describe('skill 文件读写', () => {
  it('writePluginSkill 原子写入并返回内容；readPluginSkill 读回', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'skill-test-'));
    try {
      const spec = baseSpec();
      const content = writePluginSkill(spec, root);
      expect(readPluginSkill(spec.id, root)).toBe(content);
      expect(fs.existsSync(path.join(root, spec.id, 'SKILL.md'))).toBe(true);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });

  it('deletePluginSkill 删除文件，缺失时静默', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'skill-test-'));
    try {
      writePluginSkill(baseSpec(), root);
      deletePluginSkill('test_plugin', root);
      expect(fs.existsSync(path.join(root, 'test_plugin', 'SKILL.md'))).toBe(false);
      expect(() => deletePluginSkill('test_plugin', root)).not.toThrow();
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });

  it('ensurePluginSkills 只补齐缺失文件，不覆盖已有内容', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'skill-test-'));
    try {
      const a = baseSpec();
      const b = baseSpec({ id: 'plugin_b' });
      writePluginSkill(a, root);
      const edited = '手工内容';
      fs.writeFileSync(pluginSkillPath(a.id, root), edited, 'utf8');
      ensurePluginSkills([a, b], root);
      expect(fs.readFileSync(pluginSkillPath(a.id, root), 'utf8')).toBe(edited);
      expect(fs.existsSync(pluginSkillPath(b.id, root))).toBe(true);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });

  it('回复协议只控制允许的结构化事件，产物布局保持气泡外', () => {
    expect(filterPluginGenerationArgs({ workflowId: 'p', prompt: 'secret', images: ['ref.png'] }, { ...DEFAULT_PLUGIN_RESPONSE_POLICY, prompt: 'hidden' })).toEqual({ workflowId: 'p', images: ['ref.png'] });
    expect(pluginResponseAllows({ ...DEFAULT_PLUGIN_RESPONSE_POLICY, thinking: 'hidden' }, 'thinking')).toBe(false);
    expect(pluginResponseAllows({ ...DEFAULT_PLUGIN_RESPONSE_POLICY, prompt: 'hidden' }, 'prompt')).toBe(false);
    expect(pluginResponseAllows({ ...DEFAULT_PLUGIN_RESPONSE_POLICY, route: 'hidden' }, 'route')).toBe(false);
    expect(pluginResponseAllows(DEFAULT_PLUGIN_RESPONSE_POLICY, 'thinking')).toBe(true);
  });

  it('解析完整和部分回复协议，非法字段逐项回退默认值', () => {
    expect(parsePluginResponsePolicy(`---\nname: p\nresponse:\n  thinking: hidden\n  prompt: hidden\n  route: visible\n  result: outside-bubble\n---`)).toEqual({
      thinking: 'hidden',
      prompt: 'hidden',
      route: 'visible',
      result: 'outside-bubble',
    });
    expect(parsePluginResponsePolicy(`---\nresponse:\n  thinking: invalid\n  prompt: hidden\n---`)).toEqual({
      ...DEFAULT_PLUGIN_RESPONSE_POLICY,
      prompt: 'hidden',
    });
    expect(parsePluginResponsePolicy('没有 frontmatter')).toEqual(DEFAULT_PLUGIN_RESPONSE_POLICY);
  });

  it('isAutoGeneratedSkill 识别自动生成标记', () => {
    expect(isAutoGeneratedSkill(generatePluginSkill(baseSpec()))).toBe(true);
    expect(isAutoGeneratedSkill('---\nname: x\n---\n\n# x\n\n> 由 plugin-creator 生成')).toBe(false);
  });

  it('writeCustomSkill 原子写入自定义内容（不注入自动标记）', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'skill-test-'));
    try {
      const custom = '# 手工写的 skill\n\n自定义内容';
      writeCustomSkill('test_plugin', custom, root);
      expect(readPluginSkill('test_plugin', root)).toBe(custom);
      expect(fs.existsSync(path.join(root, 'test_plugin', 'SKILL.md.custom'))).toBe(true);
      expect(isAutoGeneratedSkill(custom)).toBe(false);
      expect(() => writeCustomSkill('../evil', custom, root)).toThrow(/非法工作流插件 ID/);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });

  it('syncPluginSkill 只覆盖缺失或自动版，不覆盖自定义/LLM 版', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'skill-test-'));
    try {
      const spec = baseSpec();
      // 缺失时写入自动版
      syncPluginSkill(spec, root);
      expect(isAutoGeneratedSkill(readPluginSkill('test_plugin', root)!)).toBe(true);
      // 自动版会被重新同步（内容刷新）
      const refreshed = readPluginSkill('test_plugin', root)!;
      syncPluginSkill(spec, root);
      expect(readPluginSkill('test_plugin', root)).toBe(refreshed);
      // 自定义版不被覆盖
      const custom = '# 自定义 skill';
      writeCustomSkill('test_plugin', custom, root);
      syncPluginSkill(spec, root);
      expect(readPluginSkill('test_plugin', root)).toBe(custom);
      expect(fs.existsSync(path.join(root, 'test_plugin', 'SKILL.md.custom'))).toBe(true);
      // 自动重生成会清理自定义版本标记
      writePluginSkill(spec, root);
      expect(fs.existsSync(path.join(root, 'test_plugin', 'SKILL.md.custom'))).toBe(false);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });

  it('非法插件 ID 拒绝写入', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'skill-test-'));
    try {
      expect(() => writePluginSkill(baseSpec({ id: '../evil' }), root)).toThrow(/非法工作流插件 ID/);
      expect(() => pluginSkillPath('a b', root)).toThrow(/非法工作流插件 ID/);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });
});

it('PLUGIN_SKILLS_DIR 指向仓库 .pi/skills', () => {
  expect(PLUGIN_SKILLS_DIR).toMatch(/\.pi\/skills$/);
});
